### ISSUE TITLE
epsilon penalty questions/concerns

### ISSUE THREAD

**Issue by jondurbin** [NousResearch/finetuning-subnet#3]
https://github.com/NousResearch/finetuning-subnet/blob/c337721cfa2317a4a32e1b9591cbe9188226e4d6/constants/__init__.py#L66

I understand the purpose of the epsilon penalty, but I think there are two problems:
1. 2% is not a trivial amount, and the value doesn't decay over time, it's just a fixed penalty for having joined the network later
2. even if someone manages to beat the other models with > epsilon loss reduction, the miners with earlier blocks can just download the new model and re-commit it, meaning they'd automatically win again

Perhaps just prevent commiting the same hash?  Not sure what other mechanisms would work.

**Comment by jon-convai** [comment]
Oh, nevermind on point 2, the block changes.

**Comment by jondurbin** [comment]
Oh, looks like the block changes for any commit - never mind on point 2.
